default: Welcome.java one.java two.java three.java InputOutput.java
	javac Welcome.java
	javac one.java
	javac two.java
	javac three.java
	javac InputOutput.java

run: default
	java Welcome
clean: 
	-rm -f core *.class $(Exec)
